#!/usr/bin/env bash
# Bash script that gives you information about the school file.

# Checks if the school file exists.
if [ -e school ]; then
    echo "school file exists"
else
    echo "school file does not exist"
fi

# Checks if the school file is empty or not.
if [ -s school ] && [ -e school ]; then
    echo "school file is not empty"
else
    echo "school file is empty"
fi

# Checks if the school file is a regular file or a directory.
if [ ! -d school ] && [ -s school ] && [ -e school ]; then
    echo "school is a regular file"
fi
